"""initial schema

Revision ID: 40546b016600
Revises: 
Create Date: 2026-04-29 16:03:27.446225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40546b016600'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attribution_outputs',
    sa.Column('attribution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('attributed_effect', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=False),
    sa.Column('confidence_upper', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attribution_id')
    )
    op.create_table('comparisons',
    sa.Column('comparison_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_a_id', sa.Uuid(), nullable=False),
    sa.Column('item_b_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("item_type IN ('place', 'outing')", name='check_item_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_table('friendships',
    sa.Column('user_a_id', sa.Uuid(), nullable=False),
    sa.Column('user_b_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name='check_status'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_a_id', 'user_b_id')
    )
    op.create_table('outings',
    sa.Column('outing_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_rating', sa.Float(), nullable=True),
    sa.Column('derived_score', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'completed', 'cancelled')", name='check_outing_status'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('outing_id')
    )
    op.create_table('place_ratings',
    sa.Column('rating_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('saved_places',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'place_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=True),
    sa.Column('custom_location_name', sa.String(length=255), nullable=True),
    sa.Column('outing_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'completed', 'cancelled')", name='check_event_status'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.outing_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('outing_invitations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('outing_id', sa.Uuid(), nullable=False),
    sa.Column('rsvp_status', sa.String(length=50), nullable=False),
    sa.Column('ics_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rsvp_status IN ('pending', 'accepted', 'rejected')", name='check_outing_invitation_status'),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.outing_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'outing_id')
    )
    op.create_table('event_invitations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('rsvp_status', sa.String(length=50), nullable=False),
    sa.Column('ics_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rsvp_status IN ('pending', 'accepted', 'rejected')", name='check_event_invitation_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_invitations')
    op.drop_table('outing_invitations')
    op.drop_table('events')
    op.drop_table('saved_places')
    op.drop_table('place_ratings')
    op.drop_table('outings')
    op.drop_table('friendships')
    op.drop_table('comparisons')
    op.drop_table('attribution_outputs')
    op.drop_table('users')
    op.drop_table('places')
    # ### end Alembic commands ###
